### ISSUE TITLE
Initialization failed while creating first user 

### ISSUE THREAD

**Issue by maximelafarie** [mucahitnezir/express-starter#12]
Firstly thank you so much for creating a such starter. I'm preparing some stuff around it that may result in a future PR 😉.

The issue is that even if the Postgres starts well, when I want to make an API call to create the first user `/auth/register` (c.f. [documentation about routes](https://github.com/mucahitnezir/express-starter#authentication-endpoints)), I got the following error : 

```
postgres         | 2021-06-16 08:33:37.651 UTC [50] ERROR:  relation "users" does not exist at character 13
postgres         | 2021-06-16 08:33:37.651 UTC [50] STATEMENT:  INSERT INTO "users" ("firstName","lastName","email","password","updatedAt","createdAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *;
node-api    | Executing (default): INSERT INTO "users" ("firstName","lastName","email","password","updatedAt","createdAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *;
node-api    | POST /auth/register 500 97.217 ms - 1339
```

So maybe could you push into the repo a "starting init" SQL file to run with the Postgres at starting because the database is empty at first start and btw it throws errors.

Cheers 🖖

**Comment by mucahitnezir** [comment]
Hi @maximelafarie

Before starting the application for the first time, you need to create the database tables from the migration files.

For this, run the following command in the root directory:
```bash
$ yarn run db:migrate
```

After that you can run the application with ```yarn run start:dev``` command.

**Comment by maximelafarie** [comment]
Thank you for fast reply @mucahitnezir, I completely forgot it, thanks! 😅 

But I implement your express starter into a `docker-compose` (maybe the future PR I'll make 😉) and I really don't know how to execute this command in the `Dockerfile` I created. I tried to do something with the Dockerfile you created but I added a "development". I don't know if I'm missing something, maybe I should add a `command` instruction into the docker-compose.yml file to run migrations, idk 😕.

docker-compose.yml:
```yaml
version: "3.7"
services:
  api:
    container_name: api
    build:
      context: .
      target: dev
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://admin:pwd@postgres:5432/db
      NODE_ENV: development
      WAIT_HOSTS: postgres:5432, redis:6379
      WAIT_AFTER: 10
      PORT: 4000
    env_file:
      - .env
    ports:
      - "4000:4000"
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db

  redis:
    container_name: redis
    image: redis:6.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.3
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  db-data:
  pgadmin-data:
  redis-data:
```

Dockerfile:
```Dockerfile
# Base image
FROM node:14-alpine AS base
COPY package.json ./app/
COPY yarn.lock ./app/
WORKDIR /app
RUN yarn install
COPY . .
RUN yarn run build
EXPOSE 3000

# Prod 
FROM base as production
ENV NODE_ENV=production
COPY package.json ./usr/src/app/
COPY yarn.lock ./usr/src/app/
WORKDIR /usr/src/app
RUN yarn install --prod
COPY --from=base /app/dist/ ./dist/
COPY swagger.json ./
CMD [ "yarn", "start" ]

# Dev
FROM base as dev
RUN yarn install
COPY --from=base /app/dist/ ./dist/
COPY swagger.json ./
# RUN yarn run db:migrate
CMD yarn run db:migrate && yarn start:dev
```
